resolver: lts-11.7
packages:
- '.'
extra-deps:
- validity-0.7.0.0
- validity-path-0.3.0.1
- genvalidity-0.5.1.0
- genvalidity-hspec-0.6.1.0
- genvalidity-hspec-aeson-0.3.0.0
- genvalidity-path-0.3.0.2
- genvalidity-property-0.2.1.0
