resolver: lts-15.6
packages:
- '.'
nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/d0faafe335698e3561f222bb38cf3d765cb0c31a.tar.gz" ]
  add-gc-roots: true
  pure: true
  packages:
  - zlib
